server:
    port: 8585

spring:
    application:
       name: gatewayservice
    cloud:
        gateway:
            routes:
                - id: service_product
                  uri: http://localhost:8586
                  predicates:
                      - Path=/products/**
                      -
                - id: service_order
                  uri: http://localhost:8587
                  predicates:
                    - Path=/orders/**
